import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Login from '@/components/login/Login';
import Header from '@/components/header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Login> */}
        <Header title="parse results better" />
        <main>{children}</main>
        {/* </Login> */}
      </body>
    </html>
  );
}
